//HintName: Log.extension.g.cs
// <auto-generated/> 18:55:17
#nullable enable
namespace OneI.Logable;

[global::System.Diagnostics.DebuggerStepThrough]
public static partial class Log
{
    public static void Debug(global::System.String message, global::OneI.Logable.User p0, [global::System.Runtime.CompilerServices.CallerMemberName] global::System.String? memberName = null, [global::System.Runtime.CompilerServices.CallerFilePath] global::System.String? filePath = null, [global::System.Runtime.CompilerServices.CallerLineNumber] global::System.Int32? lineNumber = null)
    {
        var propertyValues = new global::System.Collections.Generic.List<global::OneI.Logable.Templating.Properties.PropertyValue>(1);

        propertyValues.Add(LoggerPropertyCreator.Create(p0));

        LoggerExtensions.PackageWrite(_logger, global::OneI.Logable.LogLevel.Debug, null, message, propertyValues, memberName, filePath, lineNumber);
    }
}
#nullable restore
