//HintName: Log.extension.g.cs
// <auto-generated/>
#nullable enable
namespace OneI.Logable;

[global::System.Diagnostics.DebuggerStepThrough]
public static partial class Log
{
    public static void Debug(global::System.String message, global::System.Int32 p0)
    {
        var propertyValues = new global::System.Collections.Generic.List<global::OneI.Logable.Templating.Properties.PropertyValue>(1);

        propertyValues.Add(Create(p0));

        WriteCore(global::OneI.Logable.LogLevel.Debug, null, message, propertyValues);
    }

    #region Create Property Values

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.String p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.String>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Int32 p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.Int32>(p);
    }

    #endregion Create Property Values
}
#nullable restore
