//HintName: Log.extension.g.cs
// <auto-generated/> 22:33:05
#nullable enable
namespace OneI.Logable;

[global::System.Diagnostics.DebuggerStepThrough]
public static partial class Log
{
    #region Extension Methods

    public static void Debug<T0, T1>(global::System.String message, global::System.Collections.Generic.Dictionary<global::System.Int32, global::System.Int32> p0, global::System.Nullable<global::System.Int32> p1, global::System.Object p2, global::OneI.Logable.Fakes.Model1 p3, global::OneI.Logable.Fakes.UserService.Handlers p4, global::System.String p5, global::OneI.Logable.Fakes.UserInfo p6, global::System.Object[] p7, global::System.Object p8, global::System.Collections.BitArray p9, global::OneI.Logable.Fakes.UserType p10, global::System.Collections.Generic.List<global::System.Int32> p11, global::System.Object p12, global::OneI.Logable.Fakes.UserType p13, global::System.Decimal p14, global::System.Int32 p15, global::System.Boolean p16, global::System.Boolean p17, global::System.Char p18, global::System.Char p19, global::System.SByte p20, global::System.SByte p21, global::System.Object[] p22, global::System.Collections.BitArray p23, global::System.Collections.Generic.List<global::System.Byte> p24, global::System.ValueTuple<global::System.Int32, global::System.String, global::System.Decimal> p25, T0 p26, T1 p27)
        where T0: new()
    {
        var propertyValues = new global::System.Collections.Generic.List<global::OneI.Logable.Templating.Properties.PropertyValue>(28);

        propertyValues.Add(Create(p0));
        propertyValues.Add(Create(p1));
        propertyValues.Add(Create(p2));
        propertyValues.Add(Create(p3));
        propertyValues.Add(Create(p4));
        propertyValues.Add(Create(p5));
        propertyValues.Add(Create(p6));
        propertyValues.Add(Create(p7));
        propertyValues.Add(Create(p8));
        propertyValues.Add(Create(p9));
        propertyValues.Add(Create(p10));
        propertyValues.Add(Create(p11));
        propertyValues.Add(Create(p12));
        propertyValues.Add(Create(p13));
        propertyValues.Add(Create(p14));
        propertyValues.Add(Create(p15));
        propertyValues.Add(Create(p16));
        propertyValues.Add(Create(p17));
        propertyValues.Add(Create(p18));
        propertyValues.Add(Create(p19));
        propertyValues.Add(Create(p20));
        propertyValues.Add(Create(p21));
        propertyValues.Add(Create(p22));
        propertyValues.Add(Create(p23));
        propertyValues.Add(Create(p24));
        propertyValues.Add(Create(p25));
        propertyValues.Add(new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<T0>(p26));
        propertyValues.Add(new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<T1>(p27));

        WriteCore(global::OneI.Logable.LogLevel.Debug, null, message, propertyValues);
    }

    #endregion Extension Methods

    #region Create Property Values

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Int32 p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.Int32>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Collections.Generic.Dictionary<global::System.Int32, global::System.Int32> p)
    {
        var dictionary = new global::OneI.Logable.Templating.Properties.ValueTypes.DictionaryValue();

        foreach(var item in p)
        {
            dictionary.Add(Create(item.Key), Create(item.Value));
        }

        return dictionary;
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Nullable<global::System.Int32> p)
    {
        if(p.HasValue)
        {
            return Create(p.Value);
        }

        return Create(new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<object>(null));
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Object p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.Object>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::OneI.Logable.Fakes.Model1 p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::OneI.Logable.Fakes.Model1>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::OneI.Logable.Fakes.UserService.Handlers p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::OneI.Logable.Fakes.UserService.Handlers>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.String p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.String>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::OneI.Logable.Fakes.UserInfo p)
    {
        var valueTuple = new global::OneI.Logable.Templating.Properties.ValueTypes.ObjectValue();

        valueTuple.AddProperty("Id", Create(p.Id));

        return valueTuple;
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Object[] p)
    {
        var array = new global::OneI.Logable.Templating.Properties.ValueTypes.EnumerableValue();

        foreach(var item in p)
        {
            array.AddPropertyValue(Create(item));
        }

        return array;
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Collections.BitArray p)
    {
        var array = new global::OneI.Logable.Templating.Properties.ValueTypes.EnumerableValue();

        foreach(var item in p)
        {
            array.AddPropertyValue(Create(item));
        }

        return array;
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::OneI.Logable.Fakes.UserType p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::OneI.Logable.Fakes.UserType>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Collections.Generic.List<global::System.Int32> p)
    {
        var array = new global::OneI.Logable.Templating.Properties.ValueTypes.EnumerableValue();

        foreach(var item in p)
        {
            array.AddPropertyValue(Create(item));
        }

        return array;
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Decimal p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.Decimal>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Boolean p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.Boolean>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Char p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.Char>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.SByte p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.SByte>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Byte p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.Byte>(p);
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Collections.Generic.List<global::System.Byte> p)
    {
        var array = new global::OneI.Logable.Templating.Properties.ValueTypes.EnumerableValue();

        foreach(var item in p)
        {
            array.AddPropertyValue(Create(item));
        }

        return array;
    }

    private static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.ValueTuple<global::System.Int32, global::System.String, global::System.Decimal> p)
    {
        var valueTuple = new global::OneI.Logable.Templating.Properties.ValueTypes.ObjectValue();

        valueTuple.AddProperty("A", Create(p.Item1));
        valueTuple.AddProperty("B", Create(p.Item2));
        valueTuple.AddProperty("C", Create(p.Item3));

        return valueTuple;
    }

    #endregion Create Property Values
}
#nullable restore
