//HintName: LoggerPropertyCreator.g.cs
// <auto-generated/> 18:55:17
#nullable enable
namespace OneI.Logable;

[global::System.Diagnostics.DebuggerStepThrough]
internal static class LoggerPropertyCreator
{
    public static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Int32 p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.Int32>(p);
    }

    public static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::OneI.Logable.User p)
    {
        var valueTuple = new global::OneI.Logable.Templating.Properties.ValueTypes.ObjectValue();

        valueTuple.AddProperty("Id", Create(p.Id));

        return valueTuple;
    }

}
#nullable restore
