//HintName: LoggerWriteExtensions.extension.g.cs
// <auto-generated/> 19:21:11
#nullable enable
namespace OneI.Logable;

[global::System.Diagnostics.DebuggerStepThrough]
public static partial class LoggerWriteExtensions
{
    public static void Debug(this global::OneI.Logable.ILogger logger, global::System.String message, global::System.Int32 p0, global::System.Int32 p1, global::System.Int32 p2)
    {
        var propertyValues = new global::System.Collections.Generic.List<global::OneI.Logable.Templating.Properties.PropertyValue>(3);

        propertyValues.Add(LoggerPropertyCreator.Create(p0));
        propertyValues.Add(LoggerPropertyCreator.Create(p1));
        propertyValues.Add(LoggerPropertyCreator.Create(p2));

        LoggerExtensions.PackageWrite(logger, global::OneI.Logable.LogLevel.Debug, null, message, propertyValues);
    }
}
#nullable restore
