//HintName: LoggerPropertyCreator.g.cs
// <auto-generated/> 19:21:11
#nullable enable
namespace OneI.Logable;

[global::System.Diagnostics.DebuggerStepThrough]
internal static class LoggerPropertyCreator
{
    public static global::OneI.Logable.Templating.Properties.PropertyValue Create(global::System.Int32 p)
    {
        return new global::OneI.Logable.Templating.Properties.ValueTypes.LiteralValue<global::System.Int32>(p);
    }

}
#nullable restore
