//HintName: LoggerWriteExtensions.extension.g.cs
// <auto-generated/> 18:55:17
#nullable enable
namespace OneI.Logable;

[global::System.Diagnostics.DebuggerStepThrough]
public static partial class LoggerWriteExtensions
{
}
#nullable restore
