namespace OneI.Reflectable;

/// <summary>
/// The code assets.
/// </summary>
internal static class CodeAssets
{
    /// <summary>
    /// The one type class name.
    /// </summary>
    public const string OneTypeClassName = "OneType";
    /// <summary>
    /// The one type class file name.
    /// </summary>
    public const string OneTypeClassFileName = $"{OneTypeClassName}.g.cs";
    /// <summary>
    /// The one type class content.
    /// </summary>
    public const string OneTypeClassContent = """
        // <auto-generated/>
        #nullable enable
        namespace OneI.Logable;

        using System;

        public static partial class OneType
        {
            public static Type GetType<T>()
            {
                
            }
        }
        """;
}
