namespace OneI.Logable;

internal static class CodeAssets
{
    public const string LogableNamespace = $"OneI.{Logable}";
    public const string Logable = "Logable";
    public const string LoggerFullName = $"{LogableNamespace}.ILogger";

    public const string LogClassFullName = $"{LogableNamespace}.Log";
    public const string LogExtensionsFileName = "Log.e.g.cs";
    public const string LogFileName = "Log.g.cs";
    public const string LogFileContent = """
        // <auto-generated/>
        #nullable enable
        namespace OneI.Logable;

        using System;
        using System.Collections.Generic;
        using System.Linq;
        using System.Runtime.CompilerServices;
        using OneI.Logable.Templating.Properties;

        [global::System.Diagnostics.DebuggerStepThrough]
        public static partial class Log
        {
            private static ILogger _logger = ILogger.NullLogger;

            public static void Initialize(ILogger logger)
            {
                _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            }

            public static void Initialize(Action<ILoggerConfiguration> configure)
            {
                var configuration = new LoggerConfiguration();

                configure?.Invoke(configuration);

                _logger = configuration.CreateLogger();
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool IsEnable(LogLevel logLevel)
            {
                return _logger.IsEnable(logLevel);
            }

            #region Write

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Write(LogLevel level, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, level, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Write(LogLevel level, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, level, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Write(LogLevel level, Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, level, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Write(LogLevel level, Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, level, exception, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Write(in LoggerContext context)
            {
                _logger?.Write(context);
            }

            #endregion Write

            #region Verbose

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Verbose(string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Verbose, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Verbose(string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Verbose, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Verbose(Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Verbose, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Verbose(Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Verbose, exception, message.AsMemory(), new (0));
            }

            #endregion Verbose

            #region Debug

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Debug(string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Debug, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Debug(string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Debug, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Debug(Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Debug, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Debug(Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Debug, exception, message.AsMemory(), new (0));
            }

            #endregion Debug

            #region Information

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Information(string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Information, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Information(string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Information, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Information(Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Information, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Information(Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Information, exception, message.AsMemory(), new (0));
            }

            #endregion Information

            #region Warning

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Warning(string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Warning, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Warning(string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Warning, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Warning(Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Warning, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Warning(Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Warning, exception, message.AsMemory(), new (0));
            }

            #endregion Warning

            #region Error

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Error(string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Error, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Error(string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Error, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Error(Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Error, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Error(Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Error, exception, message.AsMemory(), new (0));
            }

            #endregion Error

            #region Fatal

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Fatal(string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Fatal, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Fatal(string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Fatal, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Fatal(Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Fatal, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Fatal(Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(_logger, LogLevel.Fatal, exception, message.AsMemory(), new (0));
            }

            #endregion Fatal
        }
        #nullable restore
        """;

    public const string LoggerPropertyCreatorClassName = "LoggerPropertyCreator";
    public const string LoggerPropertyCreatorClassFileName = $"{Logable}.p.g.cs";
    public const string LoggerPropertyCreateMethodName = "Create";
    public const string LoggerPropertyCreateCalledName = $"{LoggerPropertyCreatorClassName}.{LoggerPropertyCreateMethodName}";

    public const string MessageParameterName = "message";
    public const string MessageParameterType = "global::System.String";
    public const string LogLevelParameterName = "level";
    public const string LogLevelParameterType = $"global::{LogableNamespace}.LogLevel";
    public const string ExceptionParameterName = "exception";
    public const string ExceptionParameterType = "global::System.Exception";

    public const string LoggerExtensionClassName = "LogableExtensions";
    public const string LoggerExtensionFullName = $"{LogableNamespace}.{LoggerExtensionClassName}";
    public const string LoggerExtensionClassFileName = $"{Logable}.g.cs";
    public const string LoggerExtensionExtensionClassFileName = $"{Logable}.e.g.cs";
    public const string LoggerExtensionClassContent = """
        // <auto-generated/>
        #nullable enable
        namespace OneI.Logable;

        using System;
        using System.Collections.Generic;
        using System.Diagnostics;
        using System.Linq;
        using System.Runtime.CompilerServices;
        using OneI.Logable.Templating.Properties;

        [global::System.Diagnostics.DebuggerStepThrough]
        public static partial class LogableExtensions
        {
            #region Write

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Write(this ILogger logger, LogLevel level, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, level, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Write(this ILogger logger, LogLevel level, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, level, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Write(this ILogger logger, LogLevel level, Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, level, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Write(this ILogger logger, LogLevel level, Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, level, exception, message.AsMemory(), new (0));
            }

            #endregion Write

            #region Verbose

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Verbose(this ILogger logger, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Verbose, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Verbose(this ILogger logger, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Verbose, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Verbose(this ILogger logger, Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Verbose, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Verbose(this ILogger logger, Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Verbose, exception, message.AsMemory(), new (0));
            }

            #endregion Verbose

            #region Debug

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Debug(this ILogger logger, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Debug, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Debug(this ILogger logger, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Debug, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Debug(this ILogger logger, Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Debug, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Debug(this ILogger logger, Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Debug, exception, message.AsMemory(), new (0));
            }

            #endregion Debug

            #region Information

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Information(this ILogger logger, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Information, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Information(this ILogger logger, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Information, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Information(this ILogger logger, Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Information, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Information(this ILogger logger, Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Information, exception, message.AsMemory(), new (0));
            }

            #endregion Information

            #region Warning

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Warning(this ILogger logger, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Warning, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Warning(this ILogger logger, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Warning, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Warning(this ILogger logger, Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Warning, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Warning(this ILogger logger, Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Warning, exception, message.AsMemory(), new (0));
            }

            #endregion Warning

            #region Error

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Error(this ILogger logger, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Error, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Error(this ILogger logger, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Error, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Error(this ILogger logger, Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Error, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Error(this ILogger logger, Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Error, exception, message.AsMemory(), new (0));
            }

            #endregion Error

            #region Fatal

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Fatal(this ILogger logger, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Fatal, null, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Fatal(this ILogger logger, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Fatal, null, message.AsMemory(), new (0));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static void Fatal(this ILogger logger, Exception exception, string message, [CallerFilePath] string? filePath = null, [CallerMemberName] string? member = null, [CallerLineNumber] int? line = null)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Fatal, exception, message.AsMemory(), null, filePath, member, line);
            }

            [Conditional("DEBUG")]
            public static void Fatal(this ILogger logger, Exception exception, string message, params object?[] args)
            {
                LoggerExtensions.PackageWrite(logger, LogLevel.Fatal, exception, message.AsMemory(), new (0));
            }

            #endregion Fatal
        }
        #nullable restore
        """;
}
